package com.system_design;

import java.util.HashMap;
import java.util.Map;

public class EncodeandDecodeTinyURL {
    // Encodes a URL to a shortened URL.
    // https://leetcode.com/problems/encode-and-decode-tinyurl/discuss/1110674/Encode-and-Decode-TinyURL-or-Short-and-Easy-w-explanation
    Map<Integer, String> map = new HashMap<>();

    public String encode(String longUrl) {
        map.put(longUrl.hashCode(), longUrl); //  It returns an integer or a 4 bytes value which is generated by the hashing algorithm

        return "http://tinyurl.com/"+longUrl.hashCode();
    }

    // Decodes a shortened URL to its original URL.
    public String decode(String shortUrl) {
        return map.get(Integer.parseInt(shortUrl.replace("http://tinyurl.com/", "")));
    }
}
